# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        aws.storage:
            adapter: 'aws'
            options:
                client: app.aws.s3.storage_client
                bucket: 'resumes'
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
