# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  serializer: ~
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  indexes:
    articles:
      dynamic: false
      properties:
        name:
          type: keyword
        content:
          type: text
      persistence:
        driver: orm
        model: App\Entity\Article